# Colors

WHITE = (250, 250, 250)
BLACK = (0, 0, 0)
RED = (255, 0, 0)

# Screen/Board Stuff

SCREEN_SIZE_DIVISIBLE_BY_NINE = 108
SCREEN_SIZE_MULTIPLIER = 6
SCREEN_WIDTH = SCREEN_SIZE_DIVISIBLE_BY_NINE * SCREEN_SIZE_MULTIPLIER
SCREEN_HEIGHT = SCREEN_SIZE_DIVISIBLE_BY_NINE * SCREEN_SIZE_MULTIPLIER
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
CENTER_SCREEN_X = SCREEN_SIZE[0] // 2
CENTER_SCREEN_Y = SCREEN_SIZE[1] // 2
SUDOKU_BOARD_OFFSET = SCREEN_SIZE_MULTIPLIER - 1
SUDOKU_BOARD_WIDTH = SCREEN_SIZE_DIVISIBLE_BY_NINE * SUDOKU_BOARD_OFFSET
SUDOKU_BOARD_HEIGHT = SCREEN_SIZE_DIVISIBLE_BY_NINE * SUDOKU_BOARD_OFFSET
SUDOKU_BOARD_SIZE = (SUDOKU_BOARD_WIDTH, SUDOKU_BOARD_HEIGHT)
SUDOKU_BOARD_LARGE_SQUARE_SIZE = SUDOKU_BOARD_WIDTH // 3
SUDOKU_BOARD_SMALL_SQUARE_SIZE = SUDOKU_BOARD_WIDTH // 9
