# Colors

WHITE = (250, 250, 250)
BLACK = (0, 0, 0)
LIGHTBLUE = (145, 204, 241)
RED = (255, 0, 0)
WARNINGCOLOR = (195, 121, 121)

# Screen/Board Stuff

SCREEN_SIZE_DIVISIBLE_BY_NINE = 108
SCREEN_SIZE_MULTIPLIER = 6
SCREEN_WIDTH = SCREEN_SIZE_DIVISIBLE_BY_NINE * SCREEN_SIZE_MULTIPLIER
SCREEN_HEIGHT = SCREEN_SIZE_DIVISIBLE_BY_NINE * SCREEN_SIZE_MULTIPLIER
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
CENTER_SCREEN_X = SCREEN_SIZE[0] // 2
CENTER_SCREEN_Y = SCREEN_SIZE[1] // 2
SUDOKU_BOARD_OFFSET = SCREEN_SIZE_MULTIPLIER - 1
SUDOKU_BOARD_WIDTH = SCREEN_SIZE_DIVISIBLE_BY_NINE * SUDOKU_BOARD_OFFSET
SUDOKU_BOARD_HEIGHT = SCREEN_SIZE_DIVISIBLE_BY_NINE * SUDOKU_BOARD_OFFSET
SUDOKU_BOARD_SIZE = (SUDOKU_BOARD_WIDTH, SUDOKU_BOARD_HEIGHT)
SUDOKU_BOARD_LARGE_SQUARE_SIZE = SUDOKU_BOARD_WIDTH // 3
SUDOKU_BOARD_SMALL_SQUARE_SIZE = SUDOKU_BOARD_WIDTH // 9
# Help center numbers in cells
SUDOKU_NUMBER_X_OFFSET = 25
SUDOKU_NUMBER_Y_OFFSET = 20


board = [[0, 0, 0, 2, 6, 0, 7, 0, 1],
         [6, 8, 0, 0, 7, 0, 0, 9, 0],
         [1, 9, 0, 0, 0, 4, 5, 0, 0],
         [8, 2, 0, 1, 0, 0, 0, 4, 0],
         [0, 0, 4, 6, 0, 2, 9, 0, 0],
         [0, 5, 0, 0, 0, 3, 0, 2, 8],
         [0, 0, 9, 3, 0, 0, 0, 7, 4],
         [0, 4, 0, 0, 5, 0, 0, 3, 6],
         [7, 0, 3, 0, 1, 8, 0, 0, 0]]


def isInt(value):
    valueIsInt = False
    try:
        int(value)
        valueIsInt = True
    except:
        valueIsInt = False
    return valueIsInt


def toPygameCoordinates(array_position, CENTERED_SUDOKU_ZERO_X_CORD):
    return ((int(array_position[0]) * SUDOKU_BOARD_SMALL_SQUARE_SIZE) + CENTERED_SUDOKU_ZERO_X_CORD, (int(array_position[1]) * SUDOKU_BOARD_SMALL_SQUARE_SIZE) + CENTERED_SUDOKU_ZERO_X_CORD)
